version: '3.8'
services:
  client:
    build: ./client
    container_name: clientapp_c
    ports:
      - '3000:3000'
    volumes:
      - /C:\Users\vinay\OneDrive\Desktop\web development bootcamp\Learning Projects\Google Keep Clone\client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  server:
    build: ./api
    container_name: serverapp_c
    ports:
      - '4000:4000'
    volumes:
      - /app/node_modules
      - /C:\Users\vinay\OneDrive\Desktop\web development bootcamp\Learning Projects\Google Keep Clone\api:/app
